name       : python-axolotl
version    : 0.1.42
release    : 3
source     :
    - https://github.com/tgalal/python-axolotl/archive/0.1.42.tar.gz : 26a3c43769affe9bfdf82b783684ee62fef1a2c080bdb94ed186a360bdbb50b6
license    : GPL-3.0-or-later
component  : programming.python
summary    : This is a python port of libsignal-protocol-java
description: "This is a python port of libsignal-protocol-java \n"
builddeps  :
    - python-axolotl-curve25519
    - python-cryptography
    - python-protobuf
rundeps    :
    - python-axolotl-curve25519
    - python-cryptography
    - python-protobuf
setup      : |
    %python3_setup
install    : |
    %python3_install
